language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: AGi7mqnuJZn03JGt7fQY935f3P7iVLLAwrQ+WVDKM+RTm088S1zUlNf/9uLkBSR9J/RL75yQ0HOb43B7zrR1YpdaEyG3BE0lWUOV/uvwWE/IhR5JVc1f7LsbXVs+j4DpdOh5VgzjS5K7S5PcTFeYhXznZJX1B/QTi1SRthLvU3nBXyiciHm9iIrJpmpohk3hePkr1+EA1AfGpOydVCF8SLZMGVwb/9aNGJPFB35F6Z4dmefc77MPSVamBrNjTJSb+EEASez3L7uxKKfijEA7FCHpn0DRZ34fU3WeGUU4QfdtJBWCV4C/zXFW81ItXqw9cLHZCab7EUd9WjbUbiqehLWsclTXzomawateCgahLhtdxldHLDgERv2OcYLNeAjasrOlgeLGs9+URZG/NWWY6cIO3rHqh9YA/Vjm0x1AxVU3pBEavgf6yhrzmZkIvhQiuGk8gTNh8oaMpTMfpbrdiTpy+uf0uYlZ3c39fGObcd7zN7rVHWZrfHSLz447SNVhG5XclJMLDo64E9n1rHEKZL59hPdYMGDANTIT//AeDxtAKhOM9zr3r4QRLsPfeujGv4ygF2uSsln+cvdcl2LauCrqr7ErxdMKsCy2dEp2+nYBvSBoTl2YGeYMYVEAUfaGwIxkge2zGGJKsij5aMivpbi096x4+lgyOpGQYrRSBTg=
  - secure: fbA3EKRy/D1pp9K5bLsa6SXrYenzALiRTxfVLsWt4lDJmVloW6L3y1+C5AXEuUO/ZA+c/gM1GPrxYwJKO5T0VRdyKAqUSnQ24TCZPAq1DzFQA2nEa/hZsK0cFUJSHYtOBXECHYLWNQe9RetsJGuI/8JNoH5XwYAZSLeIJoXDkxC02fa7OOafOfHyUgw2kxQnGW0LClHUg2tznViPqClbYXxJQ6ky3WhhzVcIELzsNphdQsch6dn/qC9H/tV6IABU6+SsfmQvEuKM9NOyBGy1Z8OmEjrAiAhFTuWpu/o0wBprgdYUjthVVnDEmoaGHEMcK248dIw4qI8kG5OdBQMRIrXniFGm2GchX5M6RSj6VzRYbHMm+qS1OKHvF0r1ksqRTc0Y0q5lwg21Fag0lTVOW4gCy4vbRyPybiBpCb6t4fBtwN05qWXeN6FWH98TB77BsUG//az1dPY2jXSazeyeG0qrDiiefkx/nLAupCDcgpQwNuTdLab/CRy+oUQDhdG2IooaqdYQF6kIwt8AMh9ajC/misoc7xpPG394tjS0j/mev/ErlfTTyyhnpFTRGA0Cne0mSS/o5b65pgwCOxBLxhuDpKWtsWJxhGe90cevlXNNzDL2TyZq/gyqrWcp5jbnEBDmlxqt/7aPSCP9g/Ghyps7UftFel5tCAcc4dy9aHE=
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
script:
- set -e
- travis_wait 30 mvn -q -Dmaven.test.redirectTestOutputToFile clean verify -B
- bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - emad.albloushi@gmail.com
    on_success: always
    on_failure: always
