language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
before_script:
  - sudo /etc/init.d/mysql stop
jobs:
  include:
    - stage: test
      name: "MySQL 5.6"
      jdk: openjdk8
      script: mvn -q clean verify -B -Dembedded.mysql.version=5.6 --projects vertx-sql-client,vertx-mysql-client
    - stage: test
      name: "MySQL 5.7"
      jdk: openjdk8
      script: mvn -q clean verify -B -Dembedded.mysql.version=5.7 --projects vertx-sql-client,vertx-mysql-client
    - stage: test
      name: "Postgres 9"
      jdk: openjdk8
      script: mvn -q clean verify -B -Dembedded.postgres.version=9.6 --projects vertx-sql-client,vertx-pg-client
    - stage: test
      name: "Postgres 10"
      jdk: openjdk8
      script: mvn -q clean verify -B -Dembedded.postgres.version=10.6 --projects vertx-sql-client,vertx-pg-client
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - secure: "PWmSpJmaBZq5vLE/JeaKm+6Gk+qpZo0/i+7s2djgt8Iu48XC6ROB4ns9lKJ0mQvq7a++gcNpePWs2UadSYtNoKGWXF+hR3N22BHwVFu0BxVcTFAktaRiQ77Dl55fDWv2bIquAy2izsxOKvWYsNZOyAfA3HkH0XqBNBiNTqNcR6wanrRfgr8lJZIHOrUof2iamfgG/QFhMiRNf0u+Pp+4UuqVuKuO+j+vtuexXk42C+16jHWpQBeHrb+HrXrnK/2fB4kxcn1i0mR2auKxnqSnDVvxNbgXt/gjryJK9rZPjD2H8HxXgz+IbLeC9TVWf3P9JH4hlGSXWT0ah1RthQ/fjsF01mDxG5lIy81ShncRn58l00YmkKxk6X7famL+OJ0wFtvF0tAr4oQ8MZYi2M0+aJpGz27fi2CvUe9g3xcgmGkhhUyeu5+xBN7oWlBpj2Jk2qKtKw771fogY27kFCZEKY8ezwi+Twje8woWO2qgNpQ3AJ3SGTeXbZTGlKWLN/0DCtXxxX30z9W5Dn6MQ7A7o0gbbOnrNsa0eNjjbUqpUE34Z6nGX+MMLUfBbmFlxoJ2nRMejeOTB0bviY3i1XkbghDXwuruSexfk4UZYrUIzWgSa7MDH8rXcugiQLxtsMe+NYmY+2Urxyh7Wbk7ibW3HSrH8VEASt9aVQwXW1A6owI="
    on_success: always
    on_failure: always
